---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "picard_intervallisttobed"
description: Creates an BED file from an interval list file
keywords:
  - bed
  - interval list
  - picard
  - convert
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing metadata
          e.g. [ id:'baits']
    - interval_list:
        type: file
        description: Input interval list file
        pattern: "*.interval_list"
output:
  - intervallist:
      - meta:
          type: map
          description: |
            Groovy Map containing metadata
            e.g. [ id:'baits']
      - "*.bed":
          type: file
          description: BED file
          pattern: "*.bed"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@znorgaard"
maintainers:
  - "@znorgaard"
