name: TMB
description: |
  Calculates Tumor Mutational Burden (TMB) from a VCF using pyTMB, optionally restricting to a target region and exporting a filtered VCF.
keywords:
  - tmb
  - vcf
  - mutational burden
  - cancer
  - pyTMB
tools:
  - name: pyTMB
    homepage: https://github.com/bioinfo-pf-curie/TMB
    description: Tool for calculating tumor mutational burden (TMB) from annotated VCFs.
    licence: MIT
    identifier: biotools:pytmb
    authors:
      - nservant
      - tomgutman
      - rhagenson

    version: "1.3.0"
input:
  - name: meta
    type: map
    description: Metadata object containing sample information (e.g. id).
    required: true
  - name: vcf
    type: file
    description: Input VCF file.
    pattern: "*.vcf"
    required: true
  - name: meta2
    type: map
    description: Metadata for target BED (can be same as `meta`).
    required: true
  - name: targets
    type: file
    description: BED file defining target regions.
    pattern: "*.bed"
    required: true
  - name: tmb_vep_config
    type: file
    description: Configuration file for the variant database annotation tool (e.g. VEP).
    pattern: "*.yml"
    required: true
  - name: tmb_mutect2_config
    type: file
    description: Configuration file for the variant caller tool (e.g. MuTect2).
    pattern: "*.yml"
    required: true
output:
  - name: log
    type: file
    description: Log file produced by pyTMB.
    pattern: "*.tmb.log"
  - name: vcf
    type: file
    description: Exported VCF of considered variants.
    pattern: "*_export.vcf"
  - name: versions
    type: file
    description: File containing software versions.
    pattern: "versions.yml"
authors:
  - emmcauley
